[package]
name = "bacify"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
generic-array = "1.0.0"
log = "0.4.21"
serde_json = "1.0.115"
sha2 = "0.10.8"
tempfile = "3.10.1"
walkdir = "2.5.0"
