[package]
name = "bacify"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
dirs = "5.0.1"
env_logger = "0.11.3"
log = "0.4.21"
serde_json = "1.0.115"
tempfile = "3.10.1"
walkdir = "2.5.0"
